name: eventful-postgresql
version: "0.2.0"
maintainer: David Reaver
synopsis: Postgres implementations for eventful
description: Postgres implementations for eventful
maintainer: David Reaver
stability: experimental
category: Database,Eventsourcing,PostgreSQL
license: MIT
license-file: LICENSE.md

-- github: jdreaver/eventful

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.9 && < 5
  - eventful-core
  - eventful-sql-common

  - aeson
  - bytestring
  - mtl
  - persistent
  - text

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - eventful-test-helpers
      - persistent-postgresql
      - utf8-string
