name: eventful-sqlite
version: "0.2.0"
maintainer: David Reaver
synopsis: SQLite implementations for eventful
description: SQLite implementations for eventful
maintainer: David Reaver
stability: experimental
category: Database,Eventsourcing,SQLite
license: MIT
license-file: LICENSE.md

-- github: jdreaver/eventful

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.9 && < 5
  - eventful-core
  - eventful-sql-common

  - aeson
  - bytestring
  - mtl
  - persistent
  - text
  - uuid

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - eventful-test-helpers
      - persistent-sqlite
